name: Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  welcome:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: welcome
      run: echo "Welcome"
